name: Auto Fetch DoD Contracts

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pandas beautifulsoup4

      - name: Run scraper
        run: python fetchers/fetch_dod_contracts.py

      - name: Commit data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/dod_contracts.csv || echo "No file to add"
          timestamp=$(date)
          git commit -m "Auto-update DoD contracts at $timestamp" || echo "No changes to commit"
          git pull --rebase
          git push
